version: "0.0.1"
# Example API for images
services:
  adempiere.database:
    build:
      context: postgresql/
      dockerfile: Dockerfile
    container_name: ${POSTGRES_NAME}
    image: ${POSTGRES_NAME}
    restart: ${GENERIC_RESTART}
    volumes:
      - volume_postgres:/var/lib/postgresql/data
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/5432; exit $?;'"
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 10s
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - shared_network

  adempiere.grpc:
    image: ${ADEMPIERE_GRPC_SERVER_IMAGE}
    container_name: ${VUE_BACKEND_HOST}
    restart: ${GENERIC_RESTART}
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/50059; exit $?;'"
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 10s
    environment:
      DB_HOST: ${POSTGRES_NAME}
      SECRET_KEY: ${SECRET_KEY}
      SERVICES_ENABLED: ${SERVICES_ENABLED}
    depends_on:
      adempiere.database:
        condition: service_healthy
    networks:
      - shared_network

  grpc.proxy:
      image: ${ENVOY_IMAGE_NAME}
      container_name: ${ENVOY_NAME}
      volumes:
          - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
          - ./envoy/adempiere-grpc-server.pb:/data/service_definition.pb:ro
      depends_on:
        adempiere.grpc:
          condition: service_healthy
      networks:
        - shared_network

  ui.gateway:
      image: ${NGINX_IMAGE_NAME}
      container_name: ${NGINX_NAME}
      depends_on:
        - grpc.proxy
      ports:
          - 80:80
      volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./backend/:/etc/nginx/api_backend_conf.d
          - ./api/:/etc/nginx/api_conf.d
          - ./gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
          - ./api_json_errors.conf:/etc/nginx/api_json_errors.conf
          #- ./keys/api_keys.conf:/etc/nginx/api_keys.conf
      networks:
        - shared_network

networks:
  shared_network:
    name: ${DEFAULT_NETWORK}

volumes:
  volume_nginx:
    name: ${NGINX_VOLUME}
  volume_envoy:
    name: ${ENVOY_VOLUME}
  volume_postgres:
    name: ${POSTGRES_VOLUME}